name: CI

on:
  pull_request:
    branches: [master]
    
env: 
  PROJECT_REPONAME: ghctl

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.16"
      - name: Build
        run: go build
      - name: echo
        run: echo artifacts/$PROJECT_REPONAME_darwin_amd64
      - name: echo2
        run: echo "artifacts/$PROJECT_REPONAME_darwin_amd64"
      - name: "Vet: report likely mistakes in packages"
        run: go vet ./...
      - name: Unit Test
        run: go test ./... -v
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        with:
          command: monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Get version
        run: ./ghctl --version