name: Main

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
        # platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go build
    - name: Test
      run: go test ./... -v
    - name: Lint
      run: |
        go get -u golang.org/x/lint/golint
        golint ./...
    - name: "Vet: report likely mistakes in packages"
      run: go vet ./...
    - name: Get version
      run: ./ghctl --version

  # test-gopath:
  #   env:
  #     GOPATH: ${{ github.workspace }}
  #     GO111MODULE: off
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Install Go
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: 1.14.x
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #     with:
  #       path: ./src/github.com/${{ github.repository }}
  #   - name: Test
  #     run: go test ./...